### ISSUE TITLE
Error: source file could not be loaded

### ISSUE THREAD

**Issue by pavankumar2203** [shelfio/libreoffice-lambda-layer#36]
I am trying to convert some docx files to pdf using a NodeJS 12.x Lambda function with us-east-1 lambda layer. It throws an error saying "Error: source file could not be loaded". Any idea where this is going wrong ? or help troubleshoot ? 

```
2021-03-24T23:47:13.368Z	a797942e-b387-4f31-94da-bd85b3c2408c	INFO	Error: Command failed: export HOME=/tmp && /tmp/lo/instdir/program/soffice.bin --headless --norestore --invisible --nodefault --nofirststartwizard --nolockcheck --nologo --convert-to "pdf:writer_pdf_Export" /tmp/c175e8e9-26f8-4891-9a74-b2ea65658637.docx --outdir /tmp
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at doSomething (/var/task/index.js:126:29)
    at async /var/task/index.js:141:5
    at async Runtime.module.exports.handler (/var/task/index.js:105:2) {
  status: 81,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 29,
  stdout: <Buffer >,
  stderr: <Buffer >
}
Error: source file could not be loaded
```

**Comment by AlessandroAnnini** [comment]
@pavankumar2203 did you found out why this error is throwing?
