### ISSUE TITLE
"'brotli.Decompressor' object has no attribute 'decompress'"

### ISSUE THREAD

**Issue by kuharan** [shelfio/libreoffice-lambda-layer#44]
```START RequestId: xxxxx Version: $LATEST
No cached copy of LibreOffice exists, extracting tar stream from Brotli file.
[ERROR] AttributeError: 'brotli.Decompressor' object has no attribute 'decompress'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 62, in lambda_handler
    soffice_path = load_libre_office()
  File "/var/task/lambda_function.py", line 20, in load_libre_office
    buffer.write(d.decompress(chunk))

I am getting this error while doing the decompress for python3.8

**Comment by kuharan** [comment]
I figured it out myself. Used a wrong brotli library earlier instead of brotlipy.
